[package]
name = "websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
grid-rs = { path = "../.." }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

[workspace]
