name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish grid-rs-macros
        id: publish_macros
        uses: tu6ge/publish-action@v0.4.13
        continue-on-error: true
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          package: grid-rs-macros

      - name: Wait for crates.io index
        run: sleep 30

      - name: Publish grid-rs
        id: publish_grid
        uses: tu6ge/publish-action@v0.4.13
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          package: grid-rs
